name: Trigger auto deployment for grimmy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/grimmy-AutoDeployTrigger-a860ed99-7b72-431d-8d87-520cc6cf10d3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GRIMMY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GRIMMY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GRIMMY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: grimmy.azurecr.io
          registryUsername: ${{ secrets.GRIMMY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GRIMMY_REGISTRY_PASSWORD }}
          containerAppName: grimmy
          resourceGroup: grimoire_production_group
          imageToBuild: grimmy.azurecr.io/grimmy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


